# This is the compose file for live-reloading development environments.
# This should NEVER be enabled in production.
version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 9000:80
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 80
      GUNICORN_ACCESS_LOGFILE: /var/lib/pgadmin/log.log
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gale
      - POSTGRES_PASSWORD=password

volumes:
  postgresql_data:
    driver: local
  build_cache:
    driver: local
  pgadmin_data:
    driver: local
