branches: 
- main
- next
- name: beta
  prerelease: true
- name: alpha
  prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - "@semantic-release/git"
  - - "@semantic-release/exec"
    # - verifyConditionsCmd: "semantic-release-rust verify-conditions"
    -  prepareCmd: "semantic-release-rust prepare ${nextRelease.version}"
      # publishCmd: "semantic-release-rust publish"
  - - "@semantic-release/exec"
    - prepareCmd: "scripts/build_docker.sh ${nextRelease.version}"
      publishCmd: "docker push registry.digitalocean.com/runback/discord-bot"