[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core
common = { path = "../common" }
entity = { path = "entity" }
migration = { path = "migration" }
figment = { version = "0.10", features = ["toml", "env"] }
serde = "1.0.133"
serde_json = "1.0.79"
lazy_static = "1.4.0"
chrono = "0.4.19"
tokio = { version = "1.16", features = ["full"]}
futures = "0.3.19"
tracing = "0.1.29"
tracing-subscriber = { version = "*", features = ["json"] }
# Twilight.rs
twilight-cache-inmemory = "0.9.0"
twilight-gateway = "0.9.0"
twilight-http = "0.9.0"
twilight-model = "0.9.0"
twilight-standby = "0.9.0"
twilight-embed-builder = "0.9.0"
twilight-mention = "0.9.0"
twilight-util = { version = "0.9.0", features = ["full"] }