[default]
# Set the log level
rust_log = "DEBUG"

[default.storage]
database_url = "postgresql://gale:password@db/gale"
redis_url = "http://redis"

[default.events]
kafka_url = "http://kafka"

[default.auth]
keycloak_realm = "http://keycloak:8080/auth/realms/rematch"
client_id = "matchmaking"
# I would not recommend you store the client secret here, even though it's possible
# client_secret = "BE CAREFUL ABOUT HARDCODING THIS!"