[default]
# Set the log level
rust_log = "DEBUG"

[default.storage]
database_url = "postgresql://gale:password@db/gale"
redis_url = "http://redis"

# Place all rdkafka configuration settings here
[default.events.kafka_settings]
'message.timeout.ms' = "5000"
'bootstrap.servers' = "kafka:9092"

[default.auth]
keycloak_realm = "http://keycloak:8080/auth/realms/rematch"
client_id = "matchmaking"
# I would not recommend you store the client secret here, even though it's possible
# client_secret = "BE CAREFUL ABOUT HARDCODING THIS!"